a_tensor_initialization.py
=========

In [2]:
import torch
import os

In [3]:
t1 = torch.Tensor([1,2,3],device='cpu') # CPU에 텐서 생성 - 클래스의 객체로 생성
print(t1.dtype) # t1 텐서의 데이터 타입
print(t1.device) # t1 텐서의 디바이스
print(t1.requires_grad) # t1 텐서의 requires_grad 속성 - default = False
print(t1.size()) # t1 텐서의 크기
print(t1.shape) # t1 텐서의 모양

t1_cpu = t1.cpu() # t1 텐서를 cpu로 이동 -> 이미 cpu에 있기 때문에 변화없음

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
t2 = torch.tensor([1,2,3],device='cpu') # CPU에 텐서 생성 - 함수를 호출하여 생성
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

t2_cpu = t2.cpu() #t2 텐서를 cpu로 이동 -> 이미 cpu에 있기 때문에 변화없음

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [5]:
a1 = torch.tensor(1) # 텐서 객체 생성 -> 0차원 [1]
print(a1.shape, a1.ndim) # shape -> 텐서의 모양 = [], ndim-> 텐서의 차원 = 0차원
print(a1) # 텐서 내부 데이터 출력

torch.Size([]) 0
tensor(1)


In [6]:
a2 = torch.tensor([1])
print(a2.shape, a2.ndim)
print(a2)

torch.Size([1]) 1
tensor([1])


In [7]:
a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim) # shape -> 1차원에 데이터 5개 = [5], ndim -> 1차원
print(a3)

torch.Size([5]) 1
tensor([1, 2, 3, 4, 5])


In [8]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])
print(a4.shape, a4.ndim) # shape -> (1차원에 데이터 5개, 2차원에 데이터 1개) = [5,1], ndim -> 2차원
print(a4)

torch.Size([5, 1]) 2
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [9]:
a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim) # shape -> (1차원에 데이터 3개, 2차원에 데이터 2개) = [3,2], ndim -> 2차원
print(a5)

torch.Size([3, 2]) 2
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [10]:
a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim) # shape -> (1차원 : 3, 2차원 : 2, 3차원: 1) = [3,2,1], ndim -> 3
print(a6)

torch.Size([3, 2, 1]) 3
tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])


In [11]:
a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim) # (1차원 : 3, 2차원 : 1, 3차원 : 2, 4차원 : 1) = [3,1,2,1], ndim -> 4 
print(a7)

torch.Size([3, 1, 2, 1]) 4
tensor([[[[1],
          [2]]],


        [[[3],
          [4]]],


        [[[5],
          [6]]]])


In [12]:
a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim) # shape -> (1차원 : 3, 2차원 : 1, 3차원 : 2, 4차원 : 3) = [3,1,2,3], ndim -> 4
print(a8)

torch.Size([3, 1, 2, 3]) 4
tensor([[[[1, 2, 3],
          [2, 3, 4]]],


        [[[3, 1, 1],
          [4, 4, 5]]],


        [[[5, 6, 2],
          [6, 3, 1]]]])


In [13]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim) # shape -> (1차원 : 3, 2차원 : 1, 3차원 : 2, 4차원 : 3, 5차원 : 1) = [3,1,2,3,1], ndim -> 5
print(a9)

torch.Size([3, 1, 2, 3, 1]) 5
tensor([[[[[1],
           [2],
           [3]],

          [[2],
           [3],
           [4]]]],



        [[[[3],
           [1],
           [1]],

          [[4],
           [4],
           [5]]]],



        [[[[5],
           [6],
           [2]],

          [[6],
           [3],
           [1]]]]])


In [14]:
a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim) # shape -> (1차원 : 4, 2차원 : 5) = [4,5], ndim -> 2
print(a10)

torch.Size([4, 5]) 2
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])


In [15]:
a10 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim) # shape -> (1차원 : 4, 2차원 : 1, 3차원 : 5) = [4,1,5], ndim = 3
print(a10)

torch.Size([4, 1, 5]) 3
tensor([[[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5]]])


In [16]:
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
print(a11.shape,a11.ndim)
#텐서객체 생성 안됨 -> 텐서는 각 차원의 길이가 모두 동일해야 하는데 4차원의 길이가 3인것과 2인것이 존재하기 때문에 텐서를 생성할 수 없다.

ValueError: expected sequence of length 3 at dim 3 (got 2)

b_tensor_initialization_copy.py
=

In [17]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)
# 위 코드의 출력 결과를 통해 파이썬 리스트를 이용해 텐서객체를 생성하면 깊은복사가 되는것을 알 수 있다.
print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)
# 위 코드의 출력 결과를 통해 numpy를 이용해 텐서객체를 생성하면 as_tensor함수는 얕은복사로인해 원본의 수정을 반영하고
# Tensor 또는 tensor를 이용해 생성하면 깊은복사로 인해 원본의 수정을 반영하지 않는다.


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


c_tensor_initialization_constant_values.py
=

In [18]:
import torch

t1 = torch.ones(size=(5,))  # 0차원에 원소 5개를 1로 가진 텐서 생성
t1_like = torch.ones_like(input=t1) # t1과 사이즈가 동일한 크기와 데이터타입을 가진 텐서 객체를 생성하고 모든 원소를 1로 만듬
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # 0차원에 원소 6개를 0으로 가진 텐서 생성
t2_like = torch.zeros_like(input=t2) # t2와 사이즈가 동일한 크기와 데이터타입을 가진 텐서 객체를 생성하고 모든 원소를 0로 만듬
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # 0차원에 원소 6개를 초기화되지 않은 값(무작위)으로 가진 텐서 생성
t3_like = torch.empty_like(input=t3) # t3와 사이즈가 동일한 크기와 데이터타입을 가진 텐서 객체를 생성하고 모든 원소를 초기화되지 않은 값(무작위)으로 만듬
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3) # 항등행렬 생성
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([ 1.4013e-45,  0.0000e+00, -2.2015e+18,  5.2128e-43])
tensor([ 1.4013e-45,  0.0000e+00, -2.2468e+18,  5.2128e-43])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


d_tensor_initialization_random_values.py
===

In [19]:
import torch

t1 = torch.randint(low=10, high=20, size=(1,2)) #10 이상 20 미만의 랜덤 정수를 1차원 원소 2개에 넣는다.
print(t1)

t2 = torch.rand(size=(1, 3)) #1이상 3미만의 랜덤 실수를 1차원 원소 3개에 넣는다.
print(t2)

t3 = torch.randn(size=(1, 3)) #1이상 3미만의 정규분포 내의 확률의 랜덤 실수를 1차원 원소 3개에 넣는다
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) #평균 10, 표준편차 1을 가진 정규분포 내의 확률의 랜덤 실수를 3x2 텐서에 넣는다.
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3) #0부터 5까지 간격이 같은 원소3개를 1차원에 넣는다
print(t5)

t6 = torch.arange(5) #0부터 4까지 정수를 차례대로 1차원에 넣는다
print(t6)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

# seed를 설정한 시점 기준으로 rand함수는 같은 호출횟수일 때 같은 값을 출력한다.


tensor([[14, 17]])
tensor([[0.5901, 0.6124, 0.6159]])
tensor([[ 0.4781, -1.2679, -0.9556]])
tensor([[ 9.9052,  9.2344],
        [10.0432, 11.3663],
        [ 9.1996, 10.3871]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


e_tensor_type_conversion.py
=

In [20]:
import torch

a = torch.ones((2, 3)) # ones함수는 float32의 데이터타입을 가진다
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16) # 데이터타입 int16으로 2x3텐서에 1을 채워넣는다
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20. # 데이터타입 float64로 2x3텐서에 1을 채워넣고 각원소에 20 곱하기
print(c)

d = b.to(torch.int32) # 텐서 b의 데이터타입을 int32로 변경
print(d)

double_d = torch.ones(10, 2, dtype=torch.float32) # 데이터타입 double로 10x2 텐서에 1채워넣기
short_e = torch.tensor([[1, 2]], dtype=torch.short) # 데이터타입 short로 1x2 텐서의 원소를 변경
print(double_d.dtype)
print(short_e.dtype)
double_d = torch.zeros(10, 2).double() # 데이터타입 double로 10x2 텐서에 0채워넣기
short_e = torch.ones(10, 2).short() # 데이터타입 short로 10x2 텐서에 1채워넣기

print(double_d.dtype)
print(short_e.dtype)
double_g = torch.zeros(10, 2).to(torch.double) # 데이터타입 double로 10x2 텐서에 0채워넣기
short_e = torch.ones(10, 2).to(dtype=torch.short) #데이터타입 short 10x2 텐서에 1채워넣기

print(double_g.dtype)
print(short_e.dtype)
double_d = torch.zeros(10, 2).type(torch.float16) #데이터타입 double로 10x2텐서에 0채워넣기
short_e = torch.ones(10, 2). type(dtype=torch.short) #데이터타입 short 10x2 텐서에 1채워넣기

print(double_d.dtype)
print(short_e.dtype)

"""
형 변환 방법 정리
1. (tensor).to(dtype)
2. (tensor).(dtype)
3. (tensor).type(dtype)
4. torch.tensor(list,dtype=(dtype))
"""


double_f = torch.rand(5, dtype=torch.double) #랜덤
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype) # double * short = double


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float32
torch.int16
torch.float64
torch.int16
torch.float64
torch.int16
torch.float16
torch.int16
torch.float64


f_tensor_operations.py
=

In [21]:
import torch

#두 텐서의 덧셈
t1 = torch.ones(size=(2, 3)) # 2x3 텐서에 0 채우기
t2 = torch.ones(size=(2, 3)) # 2x3 텐서에 0 채우기
t3 = torch.add(t1, t2) # 두 텐서 더하기
t4 = t1 + t2 # 두 텐서 더하기
print(t3)
print(t4)

print("#" * 30)

#두 텐서의 뺄셈
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

#두 텐서의 곱셈
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

#두 텐서의 나눗셈
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


g_tensor_operations_mm.py
=

In [22]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1]) # tensor.dot = 벡터 내적
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # tensor.mm = 행렬 곱셈
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # tensor.bmm = 배치행렬 곱셈
# 배치행렬이란 여러개의 2D행렬을 하나의 텐서로 묶어서 표현한 데이터 구조
print(t7.size())


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


h_tensor_operations_matmul.py
=

In [23]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])
print(torch.matmul(t1, t2)) # torch.matmul = 행렬 곱셈 함수 -> 다양한 텐서 형태와 브로드캐스팅 지원
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])
#1차원 원소 각 10개 내의 3x4 행렬과 4x5행렬이 곱해져 3x5행렬이 나옴
#결과적으로 [10,3,5]의 형태가 됨
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])
#t9에 t10이 곱해질 때 broadcats에 의해 t9의 1차원 원소 10개 각각에 t10 텐서가 곱해져
#3x4 행렬과 4x5행렬이 곱해져 [10,3,5]의 형태가 됨

torch.Size([])
tensor(-3.9578)
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


i_tensor_broadcasting.py
=

In [24]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)
# broadcasting으로 t1원소 각각에 t2원소가 곱해짐
print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)
# broadcasting으로 t3의 1차원 원소 각각에 t4원소가 빼짐

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)
# broadcasting으로 덧셈, 뺄셈, 곱셈, 나눗셈 연산이 가능

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())
#함수를 이용한 broadcasting

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)
#t11의 3,2에 t12가 곱해짐
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)
#t13의 3,2에 t14의 3,1이 브로드캐스팅되어 3,2로 바뀐 뒤 곱해짐
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)
#t15의 3,2에 t16의 1,2이 브로드캐스팅되어 3,2로 바뀐 뒤 곱해짐
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())
#t13의 3,4,1에 t14의 3,1,1이 브로드캐스팅되어 3,4,1로 바뀐 뒤 곱해짐
print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])
#t20의 1,1이 브로드캐스팅에 의해 4,1이되고 t19의 1,4,1이 브로드캐스팅에 의해 3,4,1이 되어 더해진다
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])
#t22에 의해 t21이 3,1,7이되어 더해짐
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])
#t24의 1,3이 브로드캐스팅에 의해 3,3이 되어 더해짐
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

j_tensor_indexing_slicing.py
=

In [25]:
import torch

x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9]) # 1행 인덱싱
print(x[:, 1])  # >>> tensor([1, 6, 11]) # 모든 행의 1열 인덱싱
print(x[1, 2])  # >>> tensor(7) # 1행 2열 인덱싱
print(x[:, -1])  # >>> tensor([4, 9, 14) # 모든 행의 마지막 열 인덱싱

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]) # 1행부터 끝까지 인덱싱
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]]) #1행부터 끝까지 3열부터 끝까지 인덱싱

print("#" * 50, 2)

y = torch.zeros((6, 6)) # 6x6 텐서 0 채우기
y[1:4, 2] = 1 # 1행부터 3행까지 2열의 값을 1로 초기화
print(y)

print(y[1:4, 1:4]) # 1행부터 3행까지 1열부터 3열까지 출력

print("#" * 50, 3)

z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
) # 3x4 텐서
print(z[:2]) #0부터 1행까지 출력
print(z[1:, 1:3]) #1부터 끝까지, 1열부터 2열까지 출력
print(z[:, 1:]) #모든행, 1열부터 끝까지 출력

z[1:, 1:3] = 0 #1행부터 모든행, 1열부터 2열가지 값을 0으로 초기화
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


k_tensor_reshaping.py
=

In [26]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) #2x3 텐서
t2 = t1.view(3, 2)  # Shape becomes (3, 2) # 
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print('t2',t2)
print(t1)
print('t3',t3)
print(t1)

"""
view와 reshape의 차이

두 함수의 사용 원리와 반환 결과가 동일해보이지만 차이가 있다.
바로 contiguous 속성을 만족하지 않은 텐서에 적용이 가능하냐 여부이다.

contiguous란 메모리 내에서 자료형을 저장하는 상태에 대한 것이다.
텐서의 자료의 저장 순서가 순서대로라면 contiguous가 True이며
순서가 원래방향과 어긋나있다면 contigugous가 False이다.

view는 contiguous가 False인 텐서를 사용할 수 없으며
reshape는 사용 가능하다.
"""

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4) #1, -> 2x4텐서
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3) #1, -> 2x3텐서
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]]) #1x3x1텐서 생성

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,) # 1인 차원 삭제 1,3,1 -> 3,

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1) #1차원이 1이면 삭제 1,3,1 -> 3,1
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3]) #3, 인 텐서 생성

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1) # 1차원에 크기가 1인 차원 생성 3, -> 3,1
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3) # 1차원에 크기가 1인 차원 생성 2,3-> 2,1,3
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]]) #2,3 텐서 생성

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,) # 1차원으로 쭉 펴기 2,3 -> 6,

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]]) # 2,2,2 텐서 생성
t16 = torch.flatten(t15) # 1차원으로 펴기


t17 = torch.flatten(t15, start_dim=1) # 2차원부터 쭉 펴기

print(t16)
print('t17',t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5) # 2,3,5에 정규분포 확률의 랜덤 실수 생성
print(t18)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)))  # >>> torch.Size([5, 2, 3]) #차원의 구조 변경 2,3,5 -> 5,2,3
t18_1 = torch.permute(t18, (2, 0, 1))
print('t18_1',t18_1.is_contiguous()) # permute 사용 시 contiguous성질이 사라진다

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2,3 텐서 생성



# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
print('t20 : ',t20)
print('t20 is contiguous : ',t20.is_contiguous()) # permute 시 shape의 변화가 없다면 contiguous 성질 유지

t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print('t21 : ',t21)
print('t21 is contiguous : ',t21.is_contiguous()) # permute 시 shape의 변화가 생혀 contiguous 성질이 사라짐


# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)
print('t22 : ',t22)
print('t22 is contiguous : ',t22.is_contiguous()) # transpose도 마찬가지 contiguous 성질이 사라진다

t23 = torch.t(t19)  # Shape becomes (3, 2) # 전치 함수

print(t23)

t2 tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
t3 tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
t17 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
tensor([[[-0.0303,  0.0763, -0.1469, -0.0251, -1.2086],
         [ 0.6541, -0.1748, -0.6700,  0.7820,  0.1549],
         [-0.8908,  0.1875, -0.2166,  0.7557, -1.2399]],

        [[ 0.3925,  0.7325, -0.5350, -0.3018,  1.1425],
         [ 0.6591, -0.9338,  0.0862, -0.247

l_tensor_concat.py
=

In [27]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) #1차원 결합 -> 2,6,3
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0) # 0차원 결합 -> 8,
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0) #2차원 텐서의 0차원 결합 -> 4,3
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1) #2차원 텐서의 1차원 결합 ->2,6
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0) #2차원 텐서의 차원의 차원 0 결합 -> 6,3
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1) #2차원 텐서의 차원의 차원 1 결합 -> 2,9
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0) #3차원 텐서의 차원의 차원 0 결합 -> 2,2,3
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1) #3차원 텐서의 차원의 차원 1 결합 -> 1,4,3
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2) #3차원 텐서의 차원의 차원 2 결합  -> 1,2,6
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

m_tensor_stackin.py
=

In [28]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) #2,3 텐서 생성
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]]) #2,3 텐서 생성

t3 = torch.stack([t1, t2], dim=0) # 두개를 이어 붙이고 바깥에 차원 생성
print(t3)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0) # 각 텐서에 바깥차원 생성 후 cat 함수로 붙임
print(t3.shape, t3.equal(t4)) #  torch.stack([t1, t2], dim=0) = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)

t5 = torch.stack([t1, t2], dim=1) # 두개를 붙이고 1차원에 차원생성
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1) # 각 텐서의 1차원에 차원 생성 후 cat 함수로 붙임
print('t5',t5)
print(t5.shape, t5.equal(t6)) # torch.stack([t1, t2], dim=1) = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)

t7 = torch.stack([t1, t2], dim=2) # 2차원 원소끼리 붙임
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2) # 2차원 원소에 unsqueeze 후 cat
print(t7.shape, t7.equal(t8))
print('t7',t7)

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True
t5 tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
t7 tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


n_tensor_vstack_hstack.py
=

In [29]:
import torch

t1 = torch.tensor([1, 2, 3]) # 3, 텐서 생성
t2 = torch.tensor([4, 5, 6]) # 3, 텐서 생성
t3 = torch.vstack((t1, t2)) # 2,3 텐서
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]]) # 3,1 텐서 생성
t5 = torch.tensor([[4], [5], [6]]) # 3,1 텐서 생성
t6 = torch.vstack((t4, t5)) # 6,1 텐서
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
]) # 2,2,3 텐서 생성
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
]) # 2,2,3 텐서 생성
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8]) # 4,2,3 텐서 생성
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])
"""
vstack : 행으로 붙임
hstack : 열로 붙임
"""

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


'\nvstack : 행으로 붙임\nhstack : 열로 붙임\n'

# 숙제 후기
평소에 numpy를 자주 사용하곤 하는데 사실상 gpt에게 numpy를 사용해서 코드를 작성해달라고 하지 직접 numpy에 내장된 함수들을 써본적이 거의 없었다.
이번 과제를 통해 tensor에 대해 알게되었는데 numpy에서 자주 보았던 메서드가 보여 어떤 기능을 하는지 대충 예상할 수 있었고 numpy와 크게 다르지 않은 구조를 가지고 있는 것 같아 tensor에 대해 공부함에 거리낌 없이 진도를 나갈 수 있었다.

------
# 새롭게 알게된 것
view와 reshape부분을 나가면서 contigugous 속성에 대해 새롭게 알게되었다.
항상 리스트나 행렬같은 경우 행방향 순서로 메모리에 저장한다고 생각했지만 contigugous속성에 대해 알게되면서
꼭 행방향이 아니라 열방향 순서 메모리 저장도 가능하다는 것을 알게되었다.

그렇다면 왜 이부분이 중요한지 궁금했다
contigugous 텐서는 텐서의 원소들이 메모리에 연속적으로 저장되어있는 상태를 말한다.
연속적인 메모리 레이아웃은 데이터를 효율적으로 처리하고 다른 연산에 사용하기 쉽게 만들어준다.

Non-contigugous 텐서는 원소들이 메모리에 연속적으로 저장되어 있지 않은 텐서를 말한다.

contigugous와 Non-contigugous 중 contigugous 텐서를 유지하는 것이 좋은데 그 이유는 아래와 같다.
1. 연산속도 향상 - 연속적인 메모리 레이아웃으로 데이터에 대한 접근이 빠르고 효율적이다.
2. 하드웨어 최적화 - CPU와 GPU는 연속적인 메모리 액세스 패턴을 잘 처리한다.
3. 메모리 효율성 - 데이터를 메모리에 연속적으로 저장하므로 메모리 사용 효율성이 높아진다.
4. API호환성 - 많은 딥러닝 라이브러리와 프레임워크는 연속적인 텐서를 가정하고 설계가 되어있다.
5. 메모리 복사방지 - Non-contigugous 텐서는 연산시 메모리 복사가 필요할 수 있다.
따라서 contigugous한 텐서를 유지하는 것이 딥러닝 모델의 효율성, 성능, 및 안정성을 향상시키는데 중요하다.

특정 연산 후 텐서가 contigugous하지 않을 수 있는데 이 경우에 필요에 따라 .contigugous() 메서드나 관련 함수를 사용하여 텐서를 contigugous하게 변환할 수 있다고 한다.

이번 과제를 진행하면서 Non-contigugous한 텐서로 인해 오류가 발생한 적이 없지만 텐서의 속성에 대해 이해하게 되면서 앞으로 텐서를 조작하면서 고려해야할 사항을 알 수 있게되었다.


