a_tensor_initialization.py
=========


In [1]:
import torch

In [11]:
t1 = torch.Tensor([1,2,3],device='cpu') # CPU에 텐서 생성 - 클래스의 객체로 생성
print(t1.dtype) # t1 텐서의 데이터 타입
print(t1.device) # t1 텐서의 디바이스
print(t1.requires_grad) # t1 텐서의 requires_grad 속성 - default = False
print(t1.size()) # t1 텐서의 크기
print(t1.shape) # t1 텐서의 모양

t1_cpu = t1.cpu() # t1 텐서를 cpu로 이동 -> 이미 cpu에 있기 때문에 변화없음

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [12]:
t2 = torch.tensor([1,2,3],device='cpu') # CPU에 텐서 생성 - 함수를 호출하여 생성
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

t2_cpu = t2.cpu() #t2 텐서를 cpu로 이동 -> 이미 cpu에 있기 때문에 변화없음

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [19]:
a1 = torch.tensor(1) # 텐서 객체 생성 -> 0차원 [1]
print(a1.shape, a1.ndim) # shape -> 텐서의 모양 = [], ndim-> 텐서의 차원 = 0차원
print(a1) # 텐서 내부 데이터 출력

torch.Size([]) 0
tensor(1)


In [20]:
a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [24]:
a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim) # shape -> 1차원에 데이터 5개 = [5], ndim -> 1차원

torch.Size([5]) 1


In [25]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])
print(a4.shape, a4.ndim) # shape -> 1차원에 데이터 5개, 2차원에 데이터 1개 = [5,1], ndim -> 2차원

torch.Size([5, 1]) 2


In [26]:
a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim) # shape -> 1차원에 데이터 3개, 2차원에 데이터 2개 = [3,2], ndim -> 2차원

torch.Size([3, 2]) 2


In [27]:
a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim) # shape -> 1차원 : 3, 2차원 :2, 3차원:1 = [3,2,1], ndim -> 3

torch.Size([3, 2, 1]) 3


In [28]:
a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim) # 1차원 : 3, 2차원 : 1, 3차원 : 2, 4차원 : 1 = [3,1,2,1], ndim -> 4 

torch.Size([3, 1, 2, 1]) 4


In [29]:
a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim) # shape -> 1차원 : 3, 2차원 : 1, 3차원 : 2, 4차원 : 3 = [3,1,2,3], ndim -> 4

torch.Size([3, 1, 2, 3]) 4


In [30]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim) # shape -> 1차원 : 3, 2차원 : 1, 3차원 : 2, 4차원 : 3, 5차원 : 1 = [3,1,2,3,1], ndim -> 5

torch.Size([3, 1, 2, 3, 1]) 5


In [31]:
a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim) # shape -> 1차원 : 4, 2차원 : 5 = [4,5], ndim -> 2

torch.Size([4, 5]) 2


In [32]:
a10 = torch.tensor([
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim) # shape -> 1차원 : 4, 2차원 : 1, 3차원 :5 = [4,1,5], ndim = 3

torch.Size([4, 1, 5]) 3


In [33]:
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
print(a11.shape,a11.ndim)

#텐서객체 생성 안됨 -> 텐서는 각 차원의 길이가 모두 동일해야 하는데 4차원의 길이가 3인것과 2인것이 존재하기 때문에 텐서를 생성할 수 없다.

ValueError: expected sequence of length 3 at dim 3 (got 2)

b_tensor_initialization_copy.py
=

In [61]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)
# 위 코드의 출력 결과를 통해 파이썬 리스트를 이용해 텐서객체를 생성하면 깊은복사가 되는것을 알 수 있다.
print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)
# 위 코드의 출력 결과를 통해 numpy를 이용해 텐서객체를 생성하면 as_tensor함수는 얕은복사로인해 원본의 수정을 반영하고
# Tensor 또는 tensor를 이용해 생성하면 깊은복사로 인해 원본의 수정을 반영하지 않는다.


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


c_tensor_initialization_constant_values.py
=

In [65]:
import torch

t1 = torch.ones(size=(5,))  # 0차원에 원소 5개를 1로 가진 텐서 생성
t1_like = torch.ones_like(input=t1) # t1과 사이즈가 동일한 크기와 데이터타입을 가진 텐서 객체를 생성하고 모든 원소를 1로 만듬
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # 0차원에 원소 6개를 0으로 가진 텐서 생성
t2_like = torch.zeros_like(input=t2) # t2와 사이즈가 동일한 크기와 데이터타입을 가진 텐서 객체를 생성하고 모든 원소를 0로 만듬
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # 0차원에 원소 6개를 초기화되지 않은 값(무작위)으로 가진 텐서 생성
t3_like = torch.empty_like(input=t3) # t3와 사이즈가 동일한 크기와 데이터타입을 가진 텐서 객체를 생성하고 모든 원소를 초기화되지 않은 값(무작위)으로 만듬
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3) # 항등행렬 생성
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1.4013e-45, 0.0000e+00, 5.8080e+13, 5.3670e-43])
tensor([9.1477e-41,        nan, 1.1210e-44, 0.0000e+00])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
